c_compiler_version:            # [osx]
  - 17                         # [osx]
cxx_compiler_version:          # [osx]
  - 17                         # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - "10.13"                    # [osx and x86_64]

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
