{% set clang_variant = os.environ.get('CLANG_VARIANT', 'flang') %}
{% set flang_commit = "e7faf52da9e05f225fb5f751d18927e185e18b40" %}
{% set llvm_version = "11.0.1" %}
{% set version = llvm_version %}
{% set sha256 = "e8c7194a46233b33b215e4f1e228753ab56b57cd7ce1a18a681af4be111cef97" %}
{% set build_number = "20200126" %}

package:
  name: flang-split
  version: {{ version }}

source:
  url: https://github.com/xoviat/flang/archive/{{ flang_commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true    # [osx]
  skip: true    # [win32]
  skip: true    # [win and vc<14]
  track_features:
    - flang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - clangdev =={{ llvm_version }}
    - llvm-openmp =={{ llvm_version }}
    - llvmdev =={{ llvm_version }}
    - m2-sed
    - m2-gawk
  host:

test:
  commands:
    - flang --version

outputs:
  - name: libflang
    script: install_libflang.sh   # [unix]
    script: install_libflang.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - clangdev =={{ llvm_version }}
        - llvm-openmp =={{ llvm_version }}
        - llvmdev =={{ llvm_version }}
        - m2-sed
        - m2-gawk
      host:
      run:
        - vc 17  # [win]
        - llvm-openmp =={{ llvm_version }}

  - name: flang
    script: install_flang.sh      # [unix]
    script: install_flang.bat     # [win]
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - clangdev =={{ llvm_version }}
        - llvm-openmp =={{ llvm_version }}
        - llvmdev =={{ llvm_version }}
        - m2-sed
        - m2-gawk
      host:
      run:
        - vc 17  # [win]
        - clangdev =={{ llvm_version }}
        - llvm-openmp =={{ llvm_version }}
        - {{ pin_subpackage('libflang', exact=True) }}
    test:
      files:
        - hello_world.f90
      commands:
        # TODO - Figure out why the following line is needed.
        - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  # [win64]
        - flang hello_world.f90
        - ./a.out   # [unix]
        - a.exe     # [win]

  - name: flang_{{ target_platform }}
    run_exports:
      strong:
        - libflang >={{ version }}
    requirements:
      - {{ pin_subpackage('flang', exact=True) }}


about:
  home: http://github.com/flang-compiler/flang
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: Flang is a Fortran compiler targeting LLVM.

extra:
  recipe-maintainers:
    - isuruf
  feedstock-name: flang
