{% set clang_variant = os.environ.get('CLANG_VARIANT', 'flang') %}
{% set flang_commit = "a1ac1cdf8b37a0ff309fbb52c721ff268f9ce85c" %}
{% set llvm_version = "5.0.0" %}
{% set sha256 = "ca474cad5780595c018a049a06b0937daf5e51d34ba6e1fabb301a2754df39af" %}
{% set build_number = "2018.1.1" %}

package:
  name: flang
  version: {{ version }}

source:
  url: https://github.com/isuruf/flang/archive/{{ flang_commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true    # [osx]
  skip: true    # [win32]
  msvc_compiler: 14.0
  features:
    - vc14      # [win]
  track_features:
    - flang

requirements:
  build:
    - toolchain
    - cmake
    - clangdev =={{ llvm_version }}
    - openmp =={{ llvm_version }}
    - llvmdev =={{ llvm_version }}
    - flang-meta
    - vc 14     # [win]

test:
  files:
    - hello_world.f90
  commands:
    # TODO - Figure out why the following line is needed.
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64  # [win64]
    - flang --version
    - flang hello_world.f90
    - ./a.out   # [unix]
    - a.exe     # [win]

outputs:
  - name: libflang
    script: install_libflang.sh   # [unix]
    script: install_libflang.bat  # [win]
    requirements:
      - vc 14                     # [win]
  - name: flang
    script: install_flang.sh      # [unix]
    script: install_flang.bat     # [win]
    requirements:
      - clangdev =={{ llvm_version }}
      - openmp =={{ llvm_version }}
      - vc 14                     # [win]
      - libflang {{ version }} {{ build_number }}       # [unix]
      - libflang {{ version }} vc14_{{ build_number }}  # [win]

about:
  home: http://github.com/flang-compiler/flang
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: Flang is a Fortran compiler targeting LLVM.

extra:
  recipe-maintainers:
    - isuruf
    - xoviat
