travis:
  secure:
    BINSTAR_TOKEN: GGzsyfZJEqRt3Vh55p8gsbxIIQWkTKmRpP/hr8ptKfVea26QAzRe+SPVTqvhrGIPeHZ+LV2074qx/d3JBeT29ew2+RWN3bxrcGuEaRCccoi5wm5ssXC9y8xEMvPRQpMgo92idiQGu/W2K38EyeD6x7uaNQml01A+3zqj7S3YJFjACP48mTUkb1J89/okL3AgwWKr1smj8hvPK9Cvw1lMJ+1gYEEVwKaC5GrRvKeutJZ2A5S2UOx6Zv26w8/53HNxYC85zlktGMpiPbMWjX24pV6VxpNhbGiqfNB6wIifo12lyHVoxKafqbCxIXdeysyNypjtvP7jlbM0C0dMnUM14uScnUrS4wypuziUMX2tUDlOsfxg0E6mVbx+22PQtUOfgdzaqzSsZfBOHF0RdsO18ToNiAHyFu3agZZiLKJPyR0ygFzYL1nq1f3AA4R//h3KcTnaAlBPXDrubhxe9tSGHR+yS1QcaX4XFWcC0GvJRkPX2reLxtJaoaNcC8OonCQNwEMR52wZ+x81QOBVM0vU+tNTbL1MhR1Eqz6S/U+GTUs4jUZoekjTHV6gw5EM7xWI/aRLtBNl/UNJwK7+1glUjZTbGl7YYdLlw1F2tKW1r1VxXUkfAj3M9mgX534FLZ/bFDlJI5AZxTtz3j5V86jou+gKbsUcllVb9JStz7B+KcY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
