travis:
  secure:
    BINSTAR_TOKEN: Qg/dKqAifrwhR3xl84kyiGZbj6S5QiDlV0Wb+Hu6NYGe6Ik6HsX+QYR9OUc69+RGZ4tyjS9kDU6g5SkbL/AhVp2uOWUDPNOsGtqE+Y+t36mZNGgIRBEYY4OSbV1o/2um3f6j5Zy/Fs9e5ODf8KdFwqBI3IB0nrOpptrE9omoZcAckCXIzcHG2POtTJ4Fz3+RvHmjF0iHQc/zyHixCkzn2G0erYOUcJbuwULw8i0yw9GF9P5PxrQaABT7fNG8DrDJ7BCB0/NRVU/6lIM6BU6fgKOqKFbv1V3Xz6tu+VFxOjG/PzML9SmLJrgmVVYj74eDXQi0cg6hbC6WK3iDtrroM3VJ/j4INFUEUb31eLERER1jWRqKBOa6bsMt1Bq1PBVKdvC3ZnbPigtrMOm3ZuT68lqNg/aDSydGrHwNkRCBS946p/V5zpFk8E7nl7oCdUl1dfW4OAzsudHUpC2otIr3pakLAUFHJey2HEE2iuHBxa4MPcm5lsgRGSYi+eUUA9ihF/7QBVAUA5fyAqb+VdtZ/ApuPIs+r13lcunGogBxOMhderi58ofWvFcMpogJcBtjI72CbaKN73P/fDn2rlGU1xjnPfvwZBwpYEnBjNXD2f+9pqyl+EE03h9FabDmJnB/y+Skml/nEZRITi753/ri26ZM5+3Fx82pAKyOvysp5hk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
